In [ ]:
#uso de comandos em programação
#usando numpy as np

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [4]:
print(a)

[1 2 3]


In [5]:
b=np.array([(2,5,7),(5,3,9),(4,6,5)]) #usando o array

In [6]:
print(b)

[[2 5 7]
 [5 3 9]
 [4 6 5]]


In [7]:
c = np.ones((4,3)) #a função ondes distribui em linha e colunas

In [8]:
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
c = np.eye(5)#observe que aqui foi 5 linha e 5 colunas

In [10]:
print(c)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
